import { StyleSheet, Dimensions } from "react-native";

const windowHeight = Dimensions.get("window").height;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1B2122",
    width: "100%",
    height: "100%",
    alignItems: "center",
  },
  BorroVerde: {
    width: "100%",
    height: windowHeight * 0.5,
    position: "absolute",
    top: 0,
    right: 0,
  },
  botao: {
    justifyContent: "center",
    marginTop: 90,
  },
  botaoPerfil: {
    width: 60,
    height: 60,
    backgroundColor: "#0E0E0E",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
    borderColor: "#64E3A1",
    borderWidth: 1,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  perfil: {
    width: 30,
    height: 30,
    position: "absolute",
    alignSelf: "center",
  },
  textPerfil: {
    marginTop: 90,
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    textAlign: "center",
    color: "#EEFAFC",
  },
  containerTxt: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  containerTxt2: {
    paddingTop: windowHeight - 770,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  botaoLocal: {
    marginTop: -60,
    width: 200,
    height: 200,
    backgroundColor: "#43C69A",
    justifyContent: "center",
    borderRadius: 100,
    shadowColor: "#A4F4E4",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  textLocal: {
    marginTop: 105,
    fontFamily: "Inter_700Bold",
    fontSize: 22,
    textAlign: "center",
    color: "#EEFAFC",
  },
  icone: {
    marginTop: -35,
    width: 135,
    height: 135,
    position: "absolute",
    alignSelf: "center",
  },
  botaoCompass: {
    marginTop: -30,
    width: 70,
    height: 70,
    backgroundColor: "#43C69A",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 35,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  compass: {
    width: 50,
    height: 50,
    position: "absolute",
    alignSelf: "center",
    marginTop: 7,
  },
});
